# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from contract_agent.agent_rpc import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = "1.66.2"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in agent_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class AgentRpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
            "/contract.agent.v1.AgentRpcService/Health",
            request_serializer=agent__pb2.HealthRequest.SerializeToString,
            response_deserializer=agent__pb2.HealthResponse.FromString,
            _registered_method=True,
        )
        self.ParseFile = channel.unary_unary(
            "/contract.agent.v1.AgentRpcService/ParseFile",
            request_serializer=agent__pb2.ParseFileRequest.SerializeToString,
            response_deserializer=agent__pb2.JsonResponse.FromString,
            _registered_method=True,
        )
        self.Review = channel.unary_unary(
            "/contract.agent.v1.AgentRpcService/Review",
            request_serializer=agent__pb2.ReviewRequest.SerializeToString,
            response_deserializer=agent__pb2.JsonResponse.FromString,
            _registered_method=True,
        )
        self.Chat = channel.unary_unary(
            "/contract.agent.v1.AgentRpcService/Chat",
            request_serializer=agent__pb2.ChatRequest.SerializeToString,
            response_deserializer=agent__pb2.JsonResponse.FromString,
            _registered_method=True,
        )
        self.ChatStream = channel.unary_stream(
            "/contract.agent.v1.AgentRpcService/ChatStream",
            request_serializer=agent__pb2.ChatRequest.SerializeToString,
            response_deserializer=agent__pb2.ChatStreamResponse.FromString,
            _registered_method=True,
        )
        self.Redraft = channel.unary_unary(
            "/contract.agent.v1.AgentRpcService/Redraft",
            request_serializer=agent__pb2.RedraftRequest.SerializeToString,
            response_deserializer=agent__pb2.JsonResponse.FromString,
            _registered_method=True,
        )
        self.ReviewMultiAgent = channel.unary_unary(
            "/contract.agent.v1.AgentRpcService/ReviewMultiAgent",
            request_serializer=agent__pb2.ReviewRequest.SerializeToString,
            response_deserializer=agent__pb2.JsonResponse.FromString,
            _registered_method=True,
        )
        self.ReviewMultiAgentStream = channel.unary_stream(
            "/contract.agent.v1.AgentRpcService/ReviewMultiAgentStream",
            request_serializer=agent__pb2.ReviewRequest.SerializeToString,
            response_deserializer=agent__pb2.ChatStreamResponse.FromString,
            _registered_method=True,
        )
        self.EmbedDocument = channel.unary_unary(
            "/contract.agent.v1.AgentRpcService/EmbedDocument",
            request_serializer=agent__pb2.EmbedDocumentRequest.SerializeToString,
            response_deserializer=agent__pb2.JsonResponse.FromString,
            _registered_method=True,
        )


class AgentRpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ParseFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Review(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ChatStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Redraft(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReviewMultiAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReviewMultiAgentStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def EmbedDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AgentRpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Health": grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=agent__pb2.HealthRequest.FromString,
            response_serializer=agent__pb2.HealthResponse.SerializeToString,
        ),
        "ParseFile": grpc.unary_unary_rpc_method_handler(
            servicer.ParseFile,
            request_deserializer=agent__pb2.ParseFileRequest.FromString,
            response_serializer=agent__pb2.JsonResponse.SerializeToString,
        ),
        "Review": grpc.unary_unary_rpc_method_handler(
            servicer.Review,
            request_deserializer=agent__pb2.ReviewRequest.FromString,
            response_serializer=agent__pb2.JsonResponse.SerializeToString,
        ),
        "Chat": grpc.unary_unary_rpc_method_handler(
            servicer.Chat,
            request_deserializer=agent__pb2.ChatRequest.FromString,
            response_serializer=agent__pb2.JsonResponse.SerializeToString,
        ),
        "ChatStream": grpc.unary_stream_rpc_method_handler(
            servicer.ChatStream,
            request_deserializer=agent__pb2.ChatRequest.FromString,
            response_serializer=agent__pb2.ChatStreamResponse.SerializeToString,
        ),
        "Redraft": grpc.unary_unary_rpc_method_handler(
            servicer.Redraft,
            request_deserializer=agent__pb2.RedraftRequest.FromString,
            response_serializer=agent__pb2.JsonResponse.SerializeToString,
        ),
        "ReviewMultiAgent": grpc.unary_unary_rpc_method_handler(
            servicer.ReviewMultiAgent,
            request_deserializer=agent__pb2.ReviewRequest.FromString,
            response_serializer=agent__pb2.JsonResponse.SerializeToString,
        ),
        "ReviewMultiAgentStream": grpc.unary_stream_rpc_method_handler(
            servicer.ReviewMultiAgentStream,
            request_deserializer=agent__pb2.ReviewRequest.FromString,
            response_serializer=agent__pb2.ChatStreamResponse.SerializeToString,
        ),
        "EmbedDocument": grpc.unary_unary_rpc_method_handler(
            servicer.EmbedDocument,
            request_deserializer=agent__pb2.EmbedDocumentRequest.FromString,
            response_serializer=agent__pb2.JsonResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "contract.agent.v1.AgentRpcService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("contract.agent.v1.AgentRpcService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class AgentRpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contract.agent.v1.AgentRpcService/Health",
            agent__pb2.HealthRequest.SerializeToString,
            agent__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ParseFile(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contract.agent.v1.AgentRpcService/ParseFile",
            agent__pb2.ParseFileRequest.SerializeToString,
            agent__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Review(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contract.agent.v1.AgentRpcService/Review",
            agent__pb2.ReviewRequest.SerializeToString,
            agent__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Chat(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contract.agent.v1.AgentRpcService/Chat",
            agent__pb2.ChatRequest.SerializeToString,
            agent__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ChatStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/contract.agent.v1.AgentRpcService/ChatStream",
            agent__pb2.ChatRequest.SerializeToString,
            agent__pb2.ChatStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Redraft(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contract.agent.v1.AgentRpcService/Redraft",
            agent__pb2.RedraftRequest.SerializeToString,
            agent__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReviewMultiAgent(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contract.agent.v1.AgentRpcService/ReviewMultiAgent",
            agent__pb2.ReviewRequest.SerializeToString,
            agent__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReviewMultiAgentStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/contract.agent.v1.AgentRpcService/ReviewMultiAgentStream",
            agent__pb2.ReviewRequest.SerializeToString,
            agent__pb2.ChatStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def EmbedDocument(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contract.agent.v1.AgentRpcService/EmbedDocument",
            agent__pb2.EmbedDocumentRequest.SerializeToString,
            agent__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
